server:
  port: 8081
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: "jdbc:postgresql://localhost:5433/jobfair"
    username: "jobfair_postgresql"
    password: "123abc@A"
    driverClassName: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  services:
    profile: http://localhost:8082/profile