server:
  port: 8081

spring:
  application:
    name: identity-service
  datasource:
    url: jbdc:postgresql://localhost:5433/jobfair
    username: "jobfair_postgresql"
    password: "123abc@A"
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'